In [2]:
import numpy as np
from numpy import genfromtxt

In [3]:
#exercise 2

shoppingChallenge = genfromtxt('DS1_C4_S1_Shopping_Data_Challenge.csv', delimiter=',', skip_header=1)
shoppingChallenge

array([[  1.,  19.,  15.,  39.],
       [  2.,  21.,  15.,  81.],
       [  3.,  20.,  16.,   6.],
       [  4.,  23.,  16.,  77.],
       [  5.,  31.,  17.,  40.],
       [  6.,  22.,  17.,  76.],
       [  7.,  35.,  18.,   6.],
       [  8.,  23.,  18.,  94.],
       [  9.,  64.,  19.,   3.],
       [ 10.,  30.,  19.,  72.],
       [ 11.,  67.,  19.,  14.],
       [ 12.,  35.,  19.,  99.],
       [ 13.,  58.,  20.,  15.],
       [ 14.,  24.,  20.,  77.],
       [ 15.,  37.,  20.,  13.],
       [ 16.,  22.,  20.,  79.],
       [ 17.,  35.,  21.,  35.],
       [ 18.,  20.,  21.,  66.],
       [ 19.,  52.,  23.,  29.],
       [ 20.,  35.,  23.,  98.],
       [ 21.,  35.,  24.,  35.],
       [ 22.,  25.,  24.,  73.],
       [ 23.,  46.,  25.,   5.],
       [ 24.,  31.,  25.,  73.],
       [ 25.,  54.,  28.,  14.],
       [ 26.,  29.,  28.,  82.],
       [ 27.,  45.,  28.,  32.],
       [ 28.,  35.,  28.,  61.],
       [ 29.,  40.,  29.,  31.],
       [ 30.,  23.,  29.,  87.],
       [ 3

In [4]:
#task1 Display the details of the customers whose spending score is greater than 80. 
#Also, display the total count of these customers.

old=np.where(shoppingChallenge[:,3]>80)#filters the specific column index and returns the index of where those values are located
print(type(old))
arrayOld = np.array(old)

print(f'There are {arrayOld.size} customers who have a spending score higher than 80')

shoppingChallenge[old]#returns the actual values of my data


<class 'tuple'>
There are 30 customers who have a spending score higher than 80


array([[  2.,  21.,  15.,  81.],
       [  8.,  23.,  18.,  94.],
       [ 12.,  35.,  19.,  99.],
       [ 20.,  35.,  23.,  98.],
       [ 26.,  29.,  28.,  82.],
       [ 30.,  23.,  29.,  87.],
       [ 34.,  18.,  33.,  92.],
       [ 36.,  21.,  33.,  81.],
       [ 42.,  24.,  38.,  92.],
       [124.,  39.,  69.,  91.],
       [128.,  40.,  71.,  95.],
       [136.,  29.,  73.,  88.],
       [142.,  32.,  75.,  93.],
       [144.,  32.,  76.,  87.],
       [146.,  28.,  77.,  97.],
       [150.,  34.,  78.,  90.],
       [152.,  39.,  78.,  88.],
       [156.,  27.,  78.,  89.],
       [162.,  29.,  79.,  83.],
       [164.,  31.,  81.,  93.],
       [168.,  33.,  86.,  95.],
       [174.,  36.,  87.,  92.],
       [176.,  30.,  88.,  86.],
       [180.,  35.,  93.,  90.],
       [182.,  32.,  97.,  86.],
       [184.,  29.,  98.,  88.],
       [186.,  30.,  99.,  97.],
       [190.,  36., 103.,  85.],
       [194.,  38., 113.,  91.],
       [200.,  30., 137.,  83.]])

In [5]:
#task2 Extract and display the data of the customers who are 20 to 24 years of age.

age24 = np.where((shoppingChallenge[:,1] >= 20) & (shoppingChallenge[:,1]<=24))
shoppingChallenge[age24]

array([[  2.,  21.,  15.,  81.],
       [  3.,  20.,  16.,   6.],
       [  4.,  23.,  16.,  77.],
       [  6.,  22.,  17.,  76.],
       [  8.,  23.,  18.,  94.],
       [ 14.,  24.,  20.,  77.],
       [ 16.,  22.,  20.,  79.],
       [ 18.,  20.,  21.,  66.],
       [ 30.,  23.,  29.,  87.],
       [ 32.,  21.,  30.,  73.],
       [ 36.,  21.,  33.,  81.],
       [ 40.,  20.,  37.,  75.],
       [ 42.,  24.,  38.,  92.],
       [ 46.,  24.,  39.,  65.],
       [ 79.,  23.,  54.,  52.],
       [ 85.,  21.,  54.,  57.],
       [ 88.,  22.,  57.,  55.],
       [ 96.,  24.,  60.,  52.],
       [100.,  20.,  61.,  49.],
       [101.,  23.,  62.,  41.],
       [106.,  21.,  62.,  42.],
       [125.,  23.,  70.,  29.],
       [135.,  20.,  73.,   5.]])

In [11]:
#task3 Display the IDs of the customers with the lowest annual income and the customers with the highest.

highest_income = np.sort(shoppingChallenge)[::-1]
print(f"The ID's of the top 10 highest incomes are: \n {highest_income[0:11]} ")
print("")
lowest_income = np.sort(shoppingChallenge)
print(f"The ID's of the top 10 highest incomes are: \n {lowest_income[0:11]} ")

The ID's of the top 10 highest incomes are: 
 [[ 30.  83. 137. 200.]
 [ 18.  32. 137. 199.]
 [ 32.  74. 126. 198.]
 [ 28.  45. 126. 197.]
 [ 35.  79. 120. 196.]
 [ 16.  47. 120. 195.]
 [ 38.  91. 113. 194.]
 [  8.  33. 113. 193.]
 [ 32.  69. 103. 192.]
 [ 23.  34. 103. 191.]
 [ 36.  85. 103. 190.]] 

The ID's of the top 10 highest incomes are: 
 [[ 1. 15. 19. 39.]
 [ 2. 15. 21. 81.]
 [ 3.  6. 16. 20.]
 [ 4. 16. 23. 77.]
 [ 5. 17. 31. 40.]
 [ 6. 17. 22. 76.]
 [ 6.  7. 18. 35.]
 [ 8. 18. 23. 94.]
 [ 3.  9. 19. 64.]
 [10. 19. 30. 72.]
 [11. 14. 19. 67.]] 


In [13]:
#task2.4 Display the details of the customers who are less than 45 years of age, 
#have an annual income greater than $35k, and have a spending score greater than 75. 
#How many such customers are there in the given data?

multi_condition = np.where((shoppingChallenge[:,1] < 45) & (shoppingChallenge[:,2] >35) & (shoppingChallenge[:,3] > 75))
shoppingChallenge[multi_condition]

print(f'There are {np.array(multi_condition).size} customers that are less than 45 years,make more than 35k, and have a spending score higher than 75')
shoppingChallenge[multi_condition]

There are 26 customers that are less than 45 years,make more than 35k, and have a spending score higher than 75


array([[ 42.,  24.,  38.,  92.],
       [124.,  39.,  69.,  91.],
       [126.,  31.,  70.,  77.],
       [128.,  40.,  71.,  95.],
       [136.,  29.,  73.,  88.],
       [142.,  32.,  75.,  93.],
       [144.,  32.,  76.,  87.],
       [146.,  28.,  77.,  97.],
       [150.,  34.,  78.,  90.],
       [152.,  39.,  78.,  88.],
       [154.,  38.,  78.,  76.],
       [156.,  27.,  78.,  89.],
       [158.,  30.,  78.,  78.],
       [162.,  29.,  79.,  83.],
       [164.,  31.,  81.,  93.],
       [168.,  33.,  86.,  95.],
       [174.,  36.,  87.,  92.],
       [176.,  30.,  88.,  86.],
       [180.,  35.,  93.,  90.],
       [182.,  32.,  97.,  86.],
       [184.,  29.,  98.,  88.],
       [186.,  30.,  99.,  97.],
       [190.,  36., 103.,  85.],
       [194.,  38., 113.,  91.],
       [196.,  35., 120.,  79.],
       [200.,  30., 137.,  83.]])

In [17]:
# task2.5- During the Christmas season, the company wishes to offer random gift coupons 
# valued between $10 and $50 to all its customers. Add a new column for the gift coupons in the existing data. 
# Display the details of the customers after adding the new column.

print(shoppingChallenge.shape)

randomDiscount = np.random.randint(10,51,200)#generates 200 random values between 10 and 50 and puts it into a 1D array

newShape = randomDiscount.reshape(200,1) #reshapes it from (200,_) into a 2D array (200,1)

#newColumn = np.hstack((shoppingChallenge,newShape))
newColumn = np.append(shoppingChallenge,newShape, axis = 1)#adds both arrays together or in other words, it adds a column

newColumn

(200, 4)


array([[  1.,  19.,  15.,  39.,  34.],
       [  2.,  21.,  15.,  81.,  32.],
       [  3.,  20.,  16.,   6.,  16.],
       [  4.,  23.,  16.,  77.,  32.],
       [  5.,  31.,  17.,  40.,  15.],
       [  6.,  22.,  17.,  76.,  40.],
       [  7.,  35.,  18.,   6.,  32.],
       [  8.,  23.,  18.,  94.,  29.],
       [  9.,  64.,  19.,   3.,  36.],
       [ 10.,  30.,  19.,  72.,  49.],
       [ 11.,  67.,  19.,  14.,  16.],
       [ 12.,  35.,  19.,  99.,  48.],
       [ 13.,  58.,  20.,  15.,  32.],
       [ 14.,  24.,  20.,  77.,  35.],
       [ 15.,  37.,  20.,  13.,  37.],
       [ 16.,  22.,  20.,  79.,  23.],
       [ 17.,  35.,  21.,  35.,  46.],
       [ 18.,  20.,  21.,  66.,  31.],
       [ 19.,  52.,  23.,  29.,  27.],
       [ 20.,  35.,  23.,  98.,  36.],
       [ 21.,  35.,  24.,  35.,  25.],
       [ 22.,  25.,  24.,  73.,  11.],
       [ 23.,  46.,  25.,   5.,  27.],
       [ 24.,  31.,  25.,  73.,  21.],
       [ 25.,  54.,  28.,  14.,  30.],
       [ 26.,  29.,  28.,