In [1]:
import numpy as np
from numpy import genfromtxt

empChallenge = genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv', delimiter=',', skip_header=1)
empChallenge

array([[ 1., 22.],
       [ 2., 27.],
       [ 3., 31.],
       [ 4., 29.],
       [ 5., 27.],
       [ 6., 26.],
       [ 7., 27.],
       [ 8., 23.],
       [ 9., 27.],
       [10., 32.],
       [11., 28.],
       [12., 27.],
       [13., 22.],
       [14., 27.],
       [15., 35.],
       [16., 33.],
       [17., 28.],
       [18., 22.],
       [19., 25.],
       [20., 27.],
       [21., 37.],
       [22., 27.],
       [23., 24.],
       [24., 27.],
       [25., 28.],
       [26., 26.],
       [27., 27.],
       [28., 27.],
       [29., 29.],
       [30., 49.],
       [31., 26.],
       [32., 32.],
       [33., 26.],
       [34., 24.],
       [35., 24.],
       [36., 23.],
       [37., 28.],
       [38., 28.],
       [39., 22.],
       [40., 26.],
       [41., 32.],
       [42., 35.],
       [43., 33.],
       [44., 31.],
       [45., 30.],
       [46., 36.],
       [47., 22.],
       [48., 23.],
       [49., 32.],
       [50., 34.]])

In [2]:
#task 1.1 - Calculate the average age of the employees in the IT firm.

#avg  =empChallenge.mean(axis=0)[1]
#print(f'The average age is: {round(avg)}')

avg = np.mean(empChallenge,axis = 0)[1]
print(f'The average age is: {round(avg)}')

The average age is: 28


In [26]:
#task1.2- Display the employee codes who are above 25 years. Find the count of everyone

above25 = np.where(empChallenge[:,1] > 25) #this selects the column index 

count25 = np.array(above25) #changes above25 from a tuple to an array

print("There are", count25.size, "employees who are older than 25") #takes a count of the array size .

empChallenge[count25] #prints the new list with the employee codes that over the age of 25

There are 38 employees who are older than 25


array([[[ 2., 27.],
        [ 3., 31.],
        [ 4., 29.],
        [ 5., 27.],
        [ 6., 26.],
        [ 7., 27.],
        [ 9., 27.],
        [10., 32.],
        [11., 28.],
        [12., 27.],
        [14., 27.],
        [15., 35.],
        [16., 33.],
        [17., 28.],
        [20., 27.],
        [21., 37.],
        [22., 27.],
        [24., 27.],
        [25., 28.],
        [26., 26.],
        [27., 27.],
        [28., 27.],
        [29., 29.],
        [30., 49.],
        [31., 26.],
        [32., 32.],
        [33., 26.],
        [37., 28.],
        [38., 28.],
        [40., 26.],
        [41., 32.],
        [42., 35.],
        [43., 33.],
        [44., 31.],
        [45., 30.],
        [46., 36.],
        [49., 32.],
        [50., 34.]]])

In [27]:
#task1.3- total employees aged between 30-35 . Display all of these employees


midThirties = np.where((empChallenge[:,1] >= 30) & (empChallenge[:,1] <= 35))


print(f'There are {np.array(midThirties).size} employees that are between 30 and 35 years of age')

empChallenge[midThirties]



There are 12 employees that are between 30 and 35 years of age


array([[ 3., 31.],
       [10., 32.],
       [15., 35.],
       [16., 33.],
       [32., 32.],
       [41., 32.],
       [42., 35.],
       [43., 33.],
       [44., 31.],
       [45., 30.],
       [49., 32.],
       [50., 34.]])